apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: model-deploy
          ports:
            - containerPort: 8000
              protocol: TCP
          image: fil404/model-deploy-image:latest
      restartPolicy: Always
