version: '3'

services:
  app:
    build: .
    image: fil404/model-deploy-image:latest
    container_name: model_deploy
    ports:
      - "8000:8000"
    command: poetry run uvicorn app:app --host 0.0.0.0 --port 8000
